# Generated by Django 6.1 on 2026-09-11 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_bill_billitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Cafe POS', max_length=160)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_number', models.CharField(blank=True, max_length=80)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('invoice_footer', models.CharField(default='Thank you for visiting!', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
