# Generated by Django 6.1 on 2026-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_businesssettings_customer_address_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
