# Generated by Django 6.1 on 2026-09-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_backfill_billitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortcut_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
