# Generated by Django 6.1 on 2026-09-16 09:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_product_shortcut_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shortcut_number',
            new_name='shortcut_key',
        ),
        migrations.AlterField(
            model_name='product',
            name='shortcut_key',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='billitem',
            name='shortcut_key',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='shortcut_key',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('shortcut_key'), condition=models.Q(models.Q(('shortcut_key', ''), _negated=True), ('is_active', True)), name='unique_active_product_shortcut_key'),
        ),
    ]
