# Generated by Django 6.0.8 on 2026-09-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_create_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='khatatransaction',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
